unblee/jukebox

src/playlist.js

Playlist.validate_links function marked as TODO by @unblee was refactored with exceptions.
**I have not check whether this code is work** because I could not install this app (npm install was failed in speaker package install).

Refactor Playlist._validate_links

---

assets/css/playlist.css
assets/index.html
assets/js/playlist.js
package-lock.json
src/app.js
src/playlist.js

Related #2 
Implemented a feature that removes music from the playlist.

Implement update playlist

---

assets/js/index.js
assets/js/links-sender.js
assets/js/player.js
assets/js/playlist.js
src/player.js
src/provider/youtube.js

- Using `async/await` instead of `then` .
- Using `&&` or `||` instead of `if` .
- Using `const` instead of `let` .
- Removing unused methods.
- Change `if {\n hoge; \n}` to `if hoge;` .
- Refactoring `Playlist.humanize_time()` in `assets/js/playlist.js` .

refactor iroiro by nakazawa

---

src/app.js
src/player.js
src/playlist.js
src/provider/index.js

I add `provider/index.js` which is provider master having findByName and FindByLink methods.
`src/{player, playlist}.js` use Provider (master) instead of args on constructor.
Note: I have not check whether this program is work XD

Add provider/index (provider master)

---

assets/css/links-sender.css
assets/js/links-sender.js
src/playlist.js

Fix links sender component

---

assets/js/index.js
assets/js/player.js
src/app.js
src/player.js

:tada: :tada: :tada: :tada: :tada: :tada: :tada:

Implement "pause"

---

package.json
src/app.js
src/controller/player_controller.js
src/controller/playlist_controller.js
src/player.js
src/playlist.js
src/router.js

1. PlayerController and PlaylistController were extracted from Player and Playlist, respectively. Some of private methods on Player and Playlist were changed to public methods.
2. Router was extracted from app.js.
Router extends `koa-router` that is **new package** (you MUST execute `npm i`). `koa-route` is still in use for WebSocket (renamed as `socket_route`). So, this program uses two router. I think this is little strange, but i have no improvement idea :bow:.
Router properties and methods are for test.

Add controller and router

---

src/controller/playlist_controller.js
src/player.js
src/playlist.js

- Change source of removed index parameter.
- Add "removed" event to `src/player.js`, and use the event in `src/playlist.js` to adjust `now_playing_idx`.

Fix remove bugs

---

assets/js/playlist.js
package-lock.json
src/controller/player_controller.js
src/player.js
src/router.js

Fix #2
Implemented the feature playing specific music! Clicking a title of music plays its music.
FYI, it does not be consumed the queue even if change music using this feature.
thanks.

Play specific music

---

assets/js/index.js

Change title when it is playing music

---

assets/css/index.css
assets/css/links-sender.css
assets/css/player.css
assets/css/playlist.css
assets/index.html
assets/js/links-sender.js
assets/js/player.js
assets/js/playlist.js

fix #6 
fix #31
Cool design! :smile:

Improve UI

---

package.json

Fix dev command

---

src/player.js

I add checking shuffle mode in `Player.start_next`.

Fix shuffle on playlist loop mode

---

src/controller/player_controller.js
src/controller/playlist_controller.js
src/player.js

Stop playing music when playing music is removed

---

src/controller/playlist_controller.js
src/player.js
src/player_status_store.js
src/playlist.js
src/track.js

Add track model

---

assets/js/index.js
assets/js/player.js
assets/js/playlist.js
src/app.js
src/controller/player_controller.js
src/controller/playlist_controller.js
src/loop_mode.js
src/player.js
src/player_status.js
src/player_status_store.js
src/playlist.js
src/router.js
src/state.js

Changes:
- Extract Player status class from Player class (fixed #54).
- Create Loop mode enum (fixed #41).
- Change loop mode change UI from radio buttons to a toggle button.
- Create Player State enum.
**Caution**:
- API `/player/loop/{playlist}/{on,off}` were replaced with `/player/loop/:mode`.
- `nowPlayingContent` property was changed to getter or wathcer.
- Enums are not used in client side.
Sorry for changing many codes :bow:

Extracting player status class

---

src/controller/player_controller.js
src/player.js
src/speaker.js

I extracted Speaker class from Player class for #49.
`src/player.js` was refactored:
- Remove `_playMusic()`.
- Add `get nowPlayingStream()`.
- Use `Speaker.start()` and `Player.nowPlayingStream` instead of `Player._playMusic()` in `start()`. 
- Rename `destroy()` with `stop()`.
- Move register of stream stop event from `_playMusic()` to `constructor()`.

extract speaker from player

---

src/player.js
src/playlist.js

Fix top music when shuffle mode is on

---

src/player.js
src/speaker.js

Fix auto start next bug

---

src/player.js

This fixed a bug when last music is ended.

Fix bug when last music is ended

---

assets/css/player.css
assets/js/player.js
src/controller/player_controller.js
src/player.js
src/router.js

Implement replay button

---

assets/css/history.css
assets/css/index.css
assets/index.html
assets/js/history.js
assets/js/index.js
e2e/pages/index.js
e2e/tests/history_test.js
e2e/tests/index_test.js
src/app.js
src/controller/history_controller.js
src/history.js
src/history_item.js
src/history_store.js
src/player.js
src/router.js
tests/helper/sample_urls.js
tests/helper/store_helper.js

This implements play history ( for #52 ).
You can check the behavior of history with E2E test.
Notes:
- I think it is necessary to refactor `*.css` and E2E test, but that should be done after #81 and #89 .
- History item has a unused attribute (`updatedAt`) because I have no idea how to display the attribute well in history view.

Add play history

---

e2e/tests/history_test.js
e2e/tests/index_test.js
src/app.js
src/history.js
src/jukebox.js
src/player.js
src/player_status.js
src/playlist.js
src/router.js
tests/helper/index.js

for #89 
- Remove EventEmitter instance(`ev`) in `src/app.js`
- Create JukeBox class having `Player`, `PlayerStatus` and `Playlist` instances  in `src/jukebox.js`.
- Provide JukeBox instance on `app.context.jukebox`.
- Reload all status before each E2E test.

Remove `ev` and create JukeBox Class

---

src/player.js
src/player_status.js

This fixed to load saved volume value (In current master revision, volume value is saved to the file, but is not loaded).

Fixed volume loading

---

assets/css/index.css
assets/index.html

Close #92 
Pretty :heart: 
[Original source code](http://tholman.com/github-corners/)

Add github link

---

assets/js/playlist.js

Fix #111 
Sorry :bow: There is a miss in the previous pull request.

Add end of div element

---

assets/js/index.js

Fix the problem that the title has not updated

---

assets/js/player.js
e2e/tests/one_loop_test.js
src/player.js

Change prev/next buttons behavior to go to prev/next music in one loop mode

---

src/app.js
src/controller/history_controller.js
src/controller/player_controller.js
src/history.js
src/history_item.js
src/player.js
src/player_status.js
src/playlist.js
src/track.js

This rename `toJson` of `History`, `HistoryItem`, `PlayerStatus`, `Playlist` and `Track` and `fetchStatus` of `Player` with `serialize` (fixed #88`).

Rename toJson and fetchStatus with serialize

---

src/player.js

Fix nullexp of player.speaker in changing volume

---

assets/css/animation-badge.css
assets/css/index.css
assets/index.html
assets/js/animation-badge.js
assets/js/index.js

This add the above button to the tab name in the playlist tab.
The badge is animation for scale and color when the number of tracks is increasing or decreasing.
I have no design color sense.  Please propose the color in the animation.
Refs #120.

Add the badge of the number of tracks in playlist

---

assets/js/index.js
e2e/custom_assertions/currentTitleEquals.js
e2e/tests/index_test.js

Fix #113 
This problem was resolved in #114. But it has occurred again.

Fix the bug which title does not changed
